name = "locale-redirect"
main = "locale-redirect-worker.js"
compatibility_date = "2024-01-01"

[[routes]]
pattern = "staging.ursoftware.com/*"
zone_name = "ursoftware.com"

# 生产环境路由 (Pages 构建已完成，正式启用)
[[routes]]
pattern = "www.ursoftware.com/*"
zone_name = "ursoftware.com"

[[routes]]
pattern = "ursoftware.com/*"
zone_name = "ursoftware.com"
